### ISSUE TITLE
multi language support

### ISSUE THREAD

**Issue by tfcolin** [rthornton128/goncurses#75] opened 2023-06-20 01:20 UTC
Thanks the authors to export this useful UI library to golang. Just one suggestion:

Could you please add a "locale" parameter to Init () function to support multi language? 
As:

// #include <stdlib.h>
// #include <locale.h>
...

func Init (locale string) {
  	locale_cstr := C.CString(locale)
	C.setlocale (C.LC_ALL, locale_cstr)
	defer C.free(unsafe.Pointer(locale_cstr))
        stdscr = &Window{C.initscr()}
        ....
}

**Comment by rthornton128** [comment] 2024-08-04 15:51
As much as I understand your need, the locale library is outside the scope of ncurses, which is what goncurses is providing bindings for. I'm hesitant to conflate the two libraries. [The wiki](https://github.com/rthornton128/goncurses/wiki/Internationalization-(I18n)) provides some limited guidance on how to set the locale and some searching did reveal a few other Go libraries that are available.

Duplicate of: https://github.com/rthornton128/goncurses/issues/47 and https://github.com/rthornton128/goncurses/issues/64

**Closed by rthornton128** 2024-08-04 15:51 UTC
Labels: duplicate, wontfix

**Comment by tfcolin** [comment] 2024-08-05 01:24
Thanks for your response. I forked your repository and solved it. 

BTW, it seems that the package (https://github.com/Xuanwo/go-locale) mentioned in your wiki page can only detect the locale for current platform, not call setlocale.
